In [1]:
import tensorflow as tf

2022-07-06 20:07:53.081136: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-07-06 20:07:53.081241: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
print(tf.__version__)

2.9.1


In [14]:
vector = tf.constant(2)
vector.shape

TensorShape([])

In [11]:
scaler = tf.constant([1,2,3])
scaler.shape

TensorShape([3])

In [12]:
matrix = tf.constant([[1,2,3],[4,5,6]])
matrix.shape

TensorShape([2, 3])

In [17]:
tensor = tf.constant([[[1,2],[4,5]],[[7,8],[10,11]]])
tensor.shape

TensorShape([2, 2, 2])

In [47]:
random_1 = tf.random.uniform(minval=0, maxval=1, shape=(5,300))
random_2 = tf.random.uniform(minval=0, maxval=1, shape=(5,300)) # create random tensor value between 0 and 1 with shape (5,300)
random_1, random_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.97180855, 0.01309228, 0.43632376, ..., 0.45301652, 0.7019756 ,
         0.73632574],
        [0.53073573, 0.13519514, 0.749459  , ..., 0.4866755 , 0.24082875,
         0.27141726],
        [0.57383466, 0.98509395, 0.4752971 , ..., 0.34897637, 0.86121845,
         0.2165308 ],
        [0.19321978, 0.78584373, 0.5839782 , ..., 0.8623903 , 0.04630113,
         0.23206806],
        [0.8686609 , 0.64344823, 0.05356407, ..., 0.8403566 , 0.25263548,
         0.7322953 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.22287834, 0.7959112 , 0.6367098 , ..., 0.5709382 , 0.5071809 ,
         0.5076848 ],
        [0.78751814, 0.6679146 , 0.71467197, ..., 0.07696426, 0.3252312 ,
         0.913712  ],
        [0.6817564 , 0.41461313, 0.9175153 , ..., 0.19051826, 0.7308496 ,
         0.9337605 ],
        [0.4110571 , 0.71376264, 0.568462  , ..., 0.39385724, 0.5069138 ,
         0.8675109 ],
        [0.85902

In [48]:
multi = tf.math.multiply(random_1, random_2)
multi

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.21659507, 0.01042029, 0.27781162, ..., 0.25864446, 0.35602862,
        0.3738214 ],
       [0.417964  , 0.09029881, 0.53561735, ..., 0.03745662, 0.07832503,
        0.24799721],
       [0.39121544, 0.40843287, 0.43609235, ..., 0.06648637, 0.6294212 ,
        0.20218791],
       [0.07942437, 0.5609059 , 0.3319694 , ..., 0.33965865, 0.02347068,
        0.20132157],
       [0.74620134, 0.02111428, 0.03622011, ..., 0.78732246, 0.06184022,
        0.06060998]], dtype=float32)>

In [54]:
dot_product = tf.matmul(random_1, tf.reshape(random_2,shape=(300,5)))
dot_product

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[73.83537 , 73.50334 , 75.19647 , 67.75211 , 68.17897 ],
       [70.699646, 71.665535, 73.55864 , 67.419495, 66.564896],
       [74.01997 , 69.16658 , 72.9257  , 68.18936 , 68.28879 ],
       [77.12622 , 72.78379 , 75.84412 , 73.180214, 70.825195],
       [74.344086, 71.62138 , 73.48158 , 68.35906 , 68.87999 ]],
      dtype=float32)>

In [51]:
random_3 = tf.random.uniform(minval=0, maxval=1, shape=(224, 224, 3))
random_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6387502 , 0.08474493, 0.8060572 ],
        [0.5995687 , 0.6261076 , 0.17552257],
        [0.10115325, 0.03883791, 0.13617039],
        ...,
        [0.56977487, 0.852836  , 0.69860303],
        [0.9373528 , 0.41367555, 0.7328452 ],
        [0.7252778 , 0.6990242 , 0.32454586]],

       [[0.11828279, 0.2058295 , 0.9438791 ],
        [0.8215507 , 0.9526365 , 0.4009905 ],
        [0.98365736, 0.35035396, 0.40457082],
        ...,
        [0.36283278, 0.729545  , 0.7005391 ],
        [0.90606356, 0.57418287, 0.15147829],
        [0.470209  , 0.22388005, 0.8459579 ]],

       [[0.26301718, 0.5060494 , 0.08880913],
        [0.5012095 , 0.13469243, 0.94252884],
        [0.28385806, 0.45454574, 0.18463337],
        ...,
        [0.30101514, 0.7463821 , 0.13363981],
        [0.83439076, 0.8376223 , 0.2890997 ],
        [0.8778117 , 0.04699779, 0.29796827]],

       ...,

       [[0.77284026, 0.6573981 , 0.44034064],
        [0.32

In [59]:
min = tf.math.reduce_min(random_3, axis=1)
max = tf.math.reduce_max(random_3, axis=1)
min, max,  min.shape, max.shape

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[7.10153580e-03, 7.11655617e-03, 1.15680695e-03],
        [1.04832649e-03, 7.68053532e-03, 3.53717804e-03],
        [2.14266777e-03, 6.97493553e-04, 7.41231441e-03],
        [5.95259666e-03, 1.14083290e-03, 5.81204891e-03],
        [2.48754025e-03, 2.38645077e-03, 1.08218193e-03],
        [3.23319435e-03, 8.62205029e-03, 5.95927238e-04],
        [1.13960505e-02, 4.39417362e-03, 2.97296047e-03],
        [4.20582294e-03, 7.90441036e-03, 3.60465050e-03],
        [5.68211079e-03, 2.30193138e-04, 7.67815113e-03],
        [7.97462463e-03, 5.89776039e-03, 4.84943390e-03],
        [6.17468357e-03, 3.48091125e-04, 9.94205475e-05],
        [2.23457813e-03, 1.92797184e-03, 1.90341473e-03],
        [1.30081177e-03, 3.22854519e-03, 5.80430031e-04],
        [3.65531445e-03, 3.12495232e-03, 6.67095184e-04],
        [1.78146362e-03, 3.63290310e-03, 3.22985649e-03],
        [3.29530239e-03, 2.59399414e-04, 5.16343117e-03],
        [5.27262688e-

In [63]:
g = tf.random.uniform(minval=0, maxval=1, shape=(1,224, 224, 3))
g.shape

TensorShape([1, 224, 224, 3])

In [65]:
tf.squeeze(g).shape

TensorShape([224, 224, 3])

In [71]:
h = tf.random.uniform(shape=[10])
h

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.47385716, 0.3771237 , 0.18212843, 0.48033702, 0.6129596 ,
       0.15966558, 0.4198022 , 0.55198133, 0.2956624 , 0.28744006],
      dtype=float32)>

In [73]:
h[tf.math.argmax(h)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.6129596>

In [77]:
h.numpy()

array([0.47385716, 0.3771237 , 0.18212843, 0.48033702, 0.6129596 ,
       0.15966558, 0.4198022 , 0.55198133, 0.2956624 , 0.28744006],
      dtype=float32)

In [78]:
tf.one_hot(h.numpy(),1)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>