<a href="https://colab.research.google.com/github/choton654/tenserflow-deep-learning/blob/main/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tenserflow fundamentals

In [2]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
print(scaler.ndim);
print(vector.ndim);

0
1


In [ ]:
matrix = tf.constant([[10,10],[4,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 4,  5]], dtype=int32)>

In [ ]:
print(matrix.ndim);

2


In [ ]:
another_matrix = tf.constant([[10.1,4.2],[2.3,4.3],[.2,.3]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.1,  4.2],
       [ 2.3,  4.3],
       [ 0.2,  0.3]], dtype=float16)>

In [ ]:
print(another_matrix.ndim);

2


In [ ]:
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
print(tensor.ndim)

3


create tensor with tf.variable, diffirent between tf.constant and tf.variable

In [ ]:
changable_tensor = tf.Variable([10,7])
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangable_tensor = tf.constant([10,7])
unchangable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

Creating random tensor

In [3]:
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape=(3,3,3))
random_1
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,3,3))
random_2

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
 array([[[-1.3240396 ,  0.28785667, -0.8757901 ],
         [-0.08857018,  0.69211644,  0.84215707],
         [-0.06378496,  0.92800784, -0.6039789 ]],
 
        [[-0.1766927 ,  0.04221033,  0.29037967],
         [-0.29604465, -0.21134205,  0.01063002],
         [ 1.5165398 ,  0.27305737, -0.29925638]],
 
        [[-0.3652325 ,  0.61883307, -1.0130816 ],
         [ 0.28291714,  1.2132233 ,  0.46988967],
         [ 0.37944323, -0.6664026 ,  0.6054596 ]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
 array([[[-1.3240396 ,  0.28785667, -0.8757901 ],
         [-0.08857018,  0.69211644,  0.84215707],
         [-0.06378496,  0.92800784, -0.6039789 ]],
 
        [[-0.1766927 ,  0.04221033,  0.29037967],
         [-0.29604465, -0.21134205,  0.01063002],
         [ 1.5165398 ,  0.27305737, -0.29925638]],
 
        [[-0.3652325 ,  0.61883307, -1.0130816 ],
         [ 0.28291714,  1.2132233 ,  0.46988967],
         [ 0.37

In [37]:
not_shuffled = tf.constant([[10,7],[3,5],[4,2]])
not_shuffled
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 4,  2]], dtype=int32)>

In [36]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  5],
       [ 4,  2],
       [10,  7]], dtype=int32)>

In [48]:
tf.ones([3,4,2])

<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)>

In [64]:
import numpy as np
narray_a = np.arange(0,32,dtype=np.int32)
narray_a
tf.constant(narray_a, shape=(4,4,2))

<tf.Tensor: shape=(4, 4, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]], dtype=int32)>

In [65]:
narray_a = np.arange(1,25,dtype=np.int32)
narray_a
narray_t = tf.constant(narray_a, shape=(2,3,4))
narray_t

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [67]:
tf.size(narray_t).numpy()

24

In [68]:
print('Datatype of every element', narray_t.dtype)
print('Number of dimensions (rank)', narray_t.ndim)
print('Shape of tensor', narray_t.shape)
print('Element along the 0 axis', narray_t.shape[0])
print('Element along the last axis', narray_t.shape[-1])
print('Total number of element in our tensor', tf.size(narray_t))
print('Total number of element in our tensor', tf.size(narray_t).numpy())


Datatype of every element <dtype: 'int32'>
Number of dimensions (rank) 3
Shape of tensor (2, 3, 4)
Element along the 0 axis 2
Element along the last axis 4
Total number of element in our tensor tf.Tensor(24, shape=(), dtype=int32)
Total number of element in our tensor 24


In [78]:
narray_t[:2,:2,:1]

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 1],
        [ 5]],

       [[13],
        [17]]], dtype=int32)>

In [86]:
rank_2_tensor = tf.ones(shape=(2,2),dtype=np.int32)
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [90]:
rank_2_tensor[:,-1] # Get the last item of each of row 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [92]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # add new axis in tensor
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [1]],

       [[1],
        [1]]], dtype=int32)>

In [97]:
rank_3_tensor = tf.expand_dims(rank_2_tensor, axis=0) # another way to add dimension putting the axis
rank_3_tensor


<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 1],
        [1, 1]]], dtype=int32)>

In [98]:
rank_3_tensor + 10

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[11, 11],
        [11, 11]]], dtype=int32)>

In [99]:
tf.multiply(rank_3_tensor, 3)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[3, 3],
        [3, 3]]], dtype=int32)>

In [117]:
x = tf.constant([[10,7],[3,4],[8,9]])
y = tf.constant([[1,2],[5,6],[11,12]])
# tf.matmul(x,y) 
# inner dimension must be same in case of matmul like 3,2 and 2,2
# x.shape
# y.shape

In [114]:
x @ y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[45, 62],
       [23, 30],
       [53, 70]], dtype=int32)>

In [123]:
tf.reshape(y, shape=(2,3))
tf.matmul(x, tf.reshape(y, shape=(2,3)))
tf.matmul(x, tf.transpose(y))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 24,  92, 194],
       [ 11,  39,  81],
       [ 26,  94, 196]], dtype=int32)>