<a href="https://colab.research.google.com/github/choton654/tenserflow-deep-learning/blob/main/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tenserflow fundamentals

In [2]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [3]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
print(scaler.ndim);
print(vector.ndim);

0
1


In [6]:
matrix = tf.constant([[10,10],[4,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 4,  5]], dtype=int32)>

In [7]:
print(matrix.ndim);

2


In [8]:
another_matrix = tf.constant([[10.1,4.2],[2.3,4.3],[.2,.3]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.1,  4.2],
       [ 2.3,  4.3],
       [ 0.2,  0.3]], dtype=float16)>

In [9]:
print(another_matrix.ndim);

2


In [10]:
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
print(tensor.ndim)

3


create tensor with tf.variable, diffirent between tf.constant and tf.variable

In [12]:
changable_tensor = tf.Variable([10,7])
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [13]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
unchangable_tensor = tf.constant([10,7])
unchangable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

Creating random tensor

In [15]:
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape=(3,3,3))
random_1
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,3,3))
random_2

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
 array([[[-1.3240396 ,  0.28785667, -0.8757901 ],
         [-0.08857018,  0.69211644,  0.84215707],
         [-0.06378496,  0.92800784, -0.6039789 ]],
 
        [[-0.1766927 ,  0.04221033,  0.29037967],
         [-0.29604465, -0.21134205,  0.01063002],
         [ 1.5165398 ,  0.27305737, -0.29925638]],
 
        [[-0.3652325 ,  0.61883307, -1.0130816 ],
         [ 0.28291714,  1.2132233 ,  0.46988967],
         [ 0.37944323, -0.6664026 ,  0.6054596 ]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
 array([[[-1.3240396 ,  0.28785667, -0.8757901 ],
         [-0.08857018,  0.69211644,  0.84215707],
         [-0.06378496,  0.92800784, -0.6039789 ]],
 
        [[-0.1766927 ,  0.04221033,  0.29037967],
         [-0.29604465, -0.21134205,  0.01063002],
         [ 1.5165398 ,  0.27305737, -0.29925638]],
 
        [[-0.3652325 ,  0.61883307, -1.0130816 ],
         [ 0.28291714,  1.2132233 ,  0.46988967],
         [ 0.37

In [16]:
not_shuffled = tf.constant([[10,7],[3,5],[4,2]])
not_shuffled
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  2],
       [ 3,  5],
       [10,  7]], dtype=int32)>

In [17]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  5],
       [ 4,  2],
       [10,  7]], dtype=int32)>

In [18]:
tf.ones([3,4,2])

<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)>

In [19]:
import numpy as np
narray_a = np.arange(0,32,dtype=np.int32)
narray_a
tf.constant(narray_a, shape=(4,4,2))

<tf.Tensor: shape=(4, 4, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]], dtype=int32)>

In [20]:
narray_a = np.arange(1,25,dtype=np.int32)
narray_a
narray_t = tf.constant(narray_a, shape=(2,3,4))
narray_t

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [21]:
tf.size(narray_t).numpy()

24

In [22]:
print('Datatype of every element', narray_t.dtype)
print('Number of dimensions (rank)', narray_t.ndim)
print('Shape of tensor', narray_t.shape)
print('Element along the 0 axis', narray_t.shape[0])
print('Element along the last axis', narray_t.shape[-1])
print('Total number of element in our tensor', tf.size(narray_t))
print('Total number of element in our tensor', tf.size(narray_t).numpy())


Datatype of every element <dtype: 'int32'>
Number of dimensions (rank) 3
Shape of tensor (2, 3, 4)
Element along the 0 axis 2
Element along the last axis 4
Total number of element in our tensor tf.Tensor(24, shape=(), dtype=int32)
Total number of element in our tensor 24


In [23]:
narray_t[:2,:2,:1]

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 1],
        [ 5]],

       [[13],
        [17]]], dtype=int32)>

In [24]:
rank_2_tensor = tf.ones(shape=(2,2),dtype=np.int32)
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [25]:
rank_2_tensor[:,-1] # Get the last item of each of row 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [26]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # add new axis in tensor
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [1]],

       [[1],
        [1]]], dtype=int32)>

In [27]:
rank_3_tensor = tf.expand_dims(rank_2_tensor, axis=0) # another way to add dimension putting the axis
rank_3_tensor


<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 1],
        [1, 1]]], dtype=int32)>

In [28]:
rank_3_tensor + 10

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[11, 11],
        [11, 11]]], dtype=int32)>

In [29]:
tf.multiply(rank_3_tensor, 3)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[3, 3],
        [3, 3]]], dtype=int32)>

In [30]:
x = tf.constant([[10,7],[3,4],[8,9]])
y = tf.constant([[1,2],[5,6],[11,12]])
# tf.matmul(x,y) 
# inner dimension must be same in case of matmul like 3,2 and 2,2
# x.shape
# y.shape

In [31]:
x @ tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 52,  97, 134],
       [ 27,  50,  63],
       [ 62, 115, 148]], dtype=int32)>

In [32]:
tf.reshape(y, shape=(2,3))
tf.matmul(x, tf.reshape(y, shape=(2,3)))
tf.matmul(x, tf.transpose(y))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 24,  92, 194],
       [ 11,  39,  81],
       [ 26,  94, 196]], dtype=int32)>

In [33]:
B = tf.constant([[10,7],[1,2],[5,6]])
B.dtype

tf.int32

In [34]:
# D = tf.cast(B, dtype=tf.float16)
D = tf.cast(B, dtype=tf.int32)
D.dtype

tf.int32

In [35]:
tf.math.reduce_min(B,keepdims=True, axis=1)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[7],
       [1],
       [5]], dtype=int32)>

In [36]:
tf.math.minimum(
    B,D
)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2],
       [ 5,  6]], dtype=int32)>

In [37]:
tf.math.reduce_max(B,keepdims=True, axis=0)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[10,  7]], dtype=int32)>

In [38]:
tf.math.reduce_mean(B,0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5], dtype=int32)>

In [39]:
C = tf.constant([[1,2],[3,4]])
tf.math.reduce_sum(C)
tf.math.reduce_mean(C,0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [40]:
F = tf.constant(np.random.randint(0, 100, size=50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([47, 57, 31, 44, 74, 16,  8, 83, 92, 39, 13, 81, 64, 99, 94,  1,  0,
       27, 94, 60, 62, 58, 98, 63, 45, 97, 62, 25, 59,  7, 28,  0, 46, 59,
       20, 84, 29, 93, 74,  8, 38, 23, 73, 85,  9,  9, 73, 21, 13, 55])>

In [41]:
tf.math.reduce_min(F)
tf.math.reduce_max(F)
tf.math.reduce_mean(F)
tf.math.reduce_sum(F)
G = tf.cast(F, dtype=tf.float64) # cast tensors to float64 fot stander daviation and varience
tf.math.reduce_std(G)
tf.math.reduce_variance(G)


<tf.Tensor: shape=(), dtype=float64, numpy=946.32>

In [44]:
import tensorflow_probability as tfp
tfp.stats.variance(F)

<tf.Tensor: shape=(), dtype=int64, numpy=946>

In [45]:
tf.math.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=13>

In [48]:
F[tf.math.argmax(F)] == tf.math.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [49]:
tf.math.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [54]:
F[tf.math.argmin(F)] == tf.math.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [70]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,50))
G

G.shape

G_squeezed = tf.squeeze(G)
G, G_squeezed

(<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
 array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
       dtype=float32)>, <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7

In [85]:
tf.one_hot([1, 2, -1, 0],3,    on_value=5.0, off_value=0.1,)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.1, 5. , 0.1],
       [0.1, 0.1, 5. ],
       [0.1, 0.1, 0.1],
       [5. , 0.1, 0.1]], dtype=float32)>

In [90]:
H = tf.constant(tf.range(1,10))
H

tf.math.square(H)
tf.math.sqrt(tf.cast(H, dtype=tf.float32))
tf.math.log(tf.cast(H, dtype=tf.float32))


<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [99]:
numpy_J = tf.constant(np.array([3.,4.,5.]))
numpy_J.numpy()
tensor_J = tf.constant([3.,4.,5.])
tensor_J.dtype, numpy_J.dtype 

(tf.float32, tf.float64)