<a href="https://colab.research.google.com/github/choton654/tenserflow-deep-learning/blob/main/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tenserflow fundamentals

In [6]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [11]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [16]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [19]:
print(scaler.ndim);
print(vector.ndim);

0
1


In [26]:
matrix = tf.constant([[10,10],[4,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 4,  5]], dtype=int32)>

In [28]:
print(matrix.ndim);

2


In [33]:
another_matrix = tf.constant([[10.1,4.2],[2.3,4.3],[.2,.3]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.1,  4.2],
       [ 2.3,  4.3],
       [ 0.2,  0.3]], dtype=float16)>

In [36]:
print(another_matrix.ndim);

2


In [38]:
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [40]:
print(tensor.ndim)

3


create tensor with tf.variable, diffirent between tf.constant and tf.variable

In [42]:
changable_tensor = tf.Variable([10,7])
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [50]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [55]:
unchangable_tensor = tf.constant([10,7])
unchangable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

Creating random tensor

In [63]:
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape=(3,3,3))
random_1
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,3,3))
random_2

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
 array([[[-1.3240396 ,  0.28785667, -0.8757901 ],
         [-0.08857018,  0.69211644,  0.84215707],
         [-0.06378496,  0.92800784, -0.6039789 ]],
 
        [[-0.1766927 ,  0.04221033,  0.29037967],
         [-0.29604465, -0.21134205,  0.01063002],
         [ 1.5165398 ,  0.27305737, -0.29925638]],
 
        [[-0.3652325 ,  0.61883307, -1.0130816 ],
         [ 0.28291714,  1.2132233 ,  0.46988967],
         [ 0.37944323, -0.6664026 ,  0.6054596 ]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
 array([[[-1.3240396 ,  0.28785667, -0.8757901 ],
         [-0.08857018,  0.69211644,  0.84215707],
         [-0.06378496,  0.92800784, -0.6039789 ]],
 
        [[-0.1766927 ,  0.04221033,  0.29037967],
         [-0.29604465, -0.21134205,  0.01063002],
         [ 1.5165398 ,  0.27305737, -0.29925638]],
 
        [[-0.3652325 ,  0.61883307, -1.0130816 ],
         [ 0.28291714,  1.2132233 ,  0.46988967],
         [ 0.37